# LightGBM Optuna Training

Train LightGBM models for `crop_type` and `phenophase_name` using full spectral/index features, cyclic date features, and location features. The pipeline includes class distribution checks, outlier clipping, normalization, Optuna tuning with macro F1, and saved model artifacts.

In [1]:
from pathlib import Path
from types import SimpleNamespace
import sys

import joblib
import pandas as pd
from IPython.display import display

NOTEBOOK_ROOT = Path.cwd()
CODE_DIR = NOTEBOOK_ROOT if (NOTEBOOK_ROOT / "features_with_labels_dropna.csv").exists() else NOTEBOOK_ROOT / "Code"
sys.path.insert(0, str(CODE_DIR))

from train_lightgbm_optuna import (
    load_dataset,
    prepare_features,
    write_distribution,
    split_indices,
    fit_transform_features,
    encode_target,
    train_and_evaluate,
    set_seed,
)

DATA_PATH = CODE_DIR / "features_with_labels_dropna.csv"
OUTPUT_DIR = CODE_DIR / "lightgbm_notebook_full_date_location"
TARGETS = ["crop_type", "phenophase_name"]

TRIALS = 25
TIMEOUT = 600
SEED = 42
TEST_SIZE = 0.20
VAL_SIZE = 0.20
CLIP_LOWER = 0.01
CLIP_UPPER = 0.99

INCLUDE_DATE_FEATURES = True
INCLUDE_LOCATION = True
INCLUDE_REGION = False
NORMALIZE = True

set_seed(SEED)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
print(f"Data: {DATA_PATH}")
print(f"Outputs: {OUTPUT_DIR}")

Data: d:\!Reno\AIG\Code\features_with_labels_dropna.csv
Outputs: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location

## Load Data And Build Features

This uses all `B_*` bands, all configured vegetation/water/built-up indices, `days_to_image`, cyclic date features from `phenophase_date` and `image_date`, plus `Longitude` and `Latitude`.

In [2]:
df = load_dataset(DATA_PATH)
feature_df, feature_cols = prepare_features(
    df=df,
    include_location=INCLUDE_LOCATION,
    include_region=INCLUDE_REGION,
    add_dates=INCLUDE_DATE_FEATURES,
)

clean_mask = df[TARGETS].notna().all(axis=1) & feature_df.notna().all(axis=1)
df = df.loc[clean_mask].reset_index(drop=True)
feature_df = feature_df.loc[clean_mask].reset_index(drop=True)

print(f"Rows after cleaning: {len(df)}")
print(f"Feature count: {len(feature_cols)}")
display(pd.Series(feature_cols, name="feature").to_frame())
display(df.head())

Rows after cleaning: 4694
Feature count: 29

                      feature
0               days_to_image
1                       B_B01
2                       B_B02
3                       B_B03
4                       B_B04
5                       B_B05
6                       B_B06
7                       B_B07
8                       B_B08
9                       B_B09
10                      B_B11
11                      B_B12
12                      B_B8A
13                       NDVI
14                       NDBI
15                       NDMI
16                      GNDVI
17                        EVI
18                      MNDWI
19    phenophase_date_doy_sin
20    phenophase_date_doy_cos
21  phenophase_date_month_sin
22  phenophase_date_month_cos
23         image_date_doy_sin
24         image_date_doy_cos
25       image_date_month_sin
26       image_date_month_cos
27                  Longitude
28                   Latitude

,point_id,Longitude,Latitude,phenophase_date,image_date,days_to_image,region,crop_type,phenophase_name,B_B01,...,B_B09,B_B11,B_B12,B_B8A,NDVI,NDBI,NDMI,GNDVI,EVI,MNDWI
0,1,125.52644,49.339533,2018/6/7,2018-05-29,9,region09,soybean,Greenup,0.0645,...,0.1924,0.2362,0.1908,0.2192,0.491246,0.041906,-0.041906,0.481583,0.297246,-0.513133
1,1,125.52644,49.339533,2018/6/30,2018-06-28,2,region09,soybean,MidGreenup,31.0000,...,14.0000,49.0000,28.0000,75.0000,0.573333,-0.092593,0.092593,0.475000,-6.515152,-0.400000
2,1,125.52644,49.339533,2018/8/6,2018-07-31,6,region09,soybean,Peak,0.0262,...,0.5686,0.1975,0.0924,0.4653,0.888993,-0.340678,0.340678,0.796064,0.704068,-0.624846
3,1,125.52644,49.339533,2018/7/22,2018-07-26,4,region09,soybean,Maturity,0.0249,...,0.5670,0.2107,0.0926,0.4405,0.895717,-0.318013,0.318013,0.795810,0.701882,-0.639689
4,1,125.52644,49.339533,2018/9/12,2018-09-09,3,region09,soybean,MidSenescence,0.0194,...,0.3005,0.1745,0.0903,0.2956,0.823400,-0.173573,0.173573,0.759943,0.455230,-0.675468

## Distribution And Feature Summary

In [3]:
write_distribution(df, feature_df, OUTPUT_DIR)

for target in TARGETS:
    dist = pd.DataFrame({
        "count": df[target].value_counts(),
        "ratio": df[target].value_counts(normalize=True),
    })
    print(f"\n{target} distribution")
    display(dist)

feature_summary = feature_df.describe().T
display(feature_summary)
print(f"Distribution and feature summary saved under: {OUTPUT_DIR / 'analysis'}")

crop_type distribution

           count     ratio
crop_type
rice        2133  0.454410
corn        1371  0.292075
soybean     1190  0.253515

phenophase_name distribution

                 count     ratio
phenophase_name
Greenup            707  0.150618
MidSenescence      705  0.150192
Dormancy           691  0.147209
Maturity           671  0.142948
MidGreenup         654  0.139327
Senescence         649  0.138262
Peak               617  0.131444

,count,mean,std,min,25%,50%,75%,max
days_to_image,4694.0,4.942267,4.730796,0.000000,2.000000,4.000000,7.000000e+00,42.000000
B_B01,4694.0,0.347369,3.050129,0.000000,0.022500,0.031100,5.080000e-02,34.000000
B_B02,4694.0,0.296668,2.447366,0.000000,0.028300,0.039900,6.170000e-02,29.000000
B_B03,4694.0,0.304192,2.302770,0.009500,0.049300,0.063300,8.697500e-02,28.000000
B_B04,4694.0,0.265317,1.941116,0.004700,0.028725,0.056400,1.016000e-01,28.000000
B_B05,4694.0,0.371610,2.586491,0.011800,0.074725,0.100850,1.460500e-01,36.000000
B_B06,4694.0,0.683743,4.702681,0.011400,0.157400,0.232950,2.949750e-01,74.000000
B_B07,4694.0,0.810004,5.467108,0.011900,0.178225,0.279000,3.921000e-01,88.000000
B_B08,4694.0,0.806183,5.324031,0.017000,0.189850,0.300550,3.980000e-01,86.000000
B_B09,4694.0,0.450417,1.275878,0.011900,0.204950,0.315900,4.183000e-01,19.000000
B_B11,4694.0,0.752285,5.786850,0.011200,0.147825,0.188700,2.557750e-01,77.000000
B_B12,4694.0,0.503656,3.931615,0.007900,0.069600,0.107900,1.728750e-01,54.000000
B_B8A,4694.0,0.884638,6.030590,0.016100,0.198700,0.311600,4.131000e-01,95.000000
NDVI,4694.0,0.564748,0.273521,-0.192164,0.295470,0.569475,8.512296e-01,0.949425
NDBI,4694.0,-0.194038,0.244333,-0.668694,-0.397902,-0.266294,3.798099e-03,0.400000
NDMI,4694.0,0.194038,0.244333,-0.400000,-0.003798,0.266294,3.979019e-01,0.668694
GNDVI,4694.0,0.553868,0.208070,-0.163435,0.400074,0.561888,7.528628e-01,0.871762
EVI,4694.0,0.398326,6.535784,-245.660004,0.166704,0.352533,6.508360e-01,270.000000
MNDWI,4694.0,-0.422722,0.219329,-0.725902,-0.565227,-0.493340,-3.642007e-01,0.626229
phenophase_date_doy_sin,4694.0,-0.437304,0.510096,-0.999963,-0.932655,-0.551102,5.147875e-02,0.778764
phenophase_date_doy_cos,4694.0,-0.597902,0.437237,-1.000000,-0.941634,-0.824855,-2.794856e-01,0.572404
phenophase_date_month_sin,4694.0,-0.587116,0.403467,-1.000000,-0.866025,-0.866025,1.224647e-16,0.500000
phenophase_date_month_cos,4694.0,-0.471039,0.520311,-1.000000,-0.866025,-0.500000,-1.836970e-16,0.866025
image_date_doy_sin,4694.0,-0.431487,0.524169,-0.999963,-0.938710,-0.507415,6.861474e-02,0.829677
image_date_doy_cos,4694.0,-0.599954,0.423341,-1.000000,-0.923056,-0.834438,-2.629622e-01,0.485060
image_date_month_sin,4694.0,-0.542368,0.448189,-1.000000,-0.866025,-0.866025,1.224647e-16,0.500000
image_date_month_cos,4694.0,-0.472893,0.530508,-1.000000,-0.866025,-0.500000,-1.836970e-16,0.500000
Longitude,4694.0,128.408437,3.172222,124.101344,125.727225,126.963378,1.317259e+02,134.641549
Latitude,4694.0,47.422858,1.411510,44.223367,46.167503,47.312587,4.892686e+01,49.585681

Distribution and feature summary saved under: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\analysis

## Train/Validation/Test Split And Normalization

Outlier clipping bounds and `StandardScaler` are fit on the training split only, then applied to validation and test splits.

In [4]:
train_idx, val_idx, test_idx = split_indices(
    df=df,
    test_size=TEST_SIZE,
    val_size=VAL_SIZE,
    seed=SEED,
)

x_train, x_val, x_test, scaler, clip_bounds = fit_transform_features(
    feature_df=feature_df,
    train_idx=train_idx,
    val_idx=val_idx,
    test_idx=test_idx,
    clip_lower=CLIP_LOWER,
    clip_upper=CLIP_UPPER,
    normalize=NORMALIZE,
)

preprocessing_dir = OUTPUT_DIR / "preprocessing"
preprocessing_dir.mkdir(parents=True, exist_ok=True)
pd.Series(feature_cols, name="feature").to_csv(preprocessing_dir / "feature_columns.csv", index=False)
clip_bounds.to_csv(preprocessing_dir / "clip_bounds.csv")
if scaler is not None:
    joblib.dump(scaler, preprocessing_dir / "standard_scaler.joblib")

print(f"Split sizes: train={len(train_idx)}, val={len(val_idx)}, test={len(test_idx)}")
print(f"x_train shape: {x_train.shape}")
print(f"Saved preprocessing artifacts to: {preprocessing_dir}")
display(pd.DataFrame(x_train, columns=feature_cols).describe().T)

Split sizes: train=3004, val=751, test=939
x_train shape: (3004, 29)
Saved preprocessing artifacts to: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\preprocessing

,count,mean,std,min,25%,50%,75%,max
days_to_image,3004.0,-3.492150e-09,1.000166,-1.141763,-0.669201,-0.196639,0.512204,3.820138
B_B01,3004.0,-3.809618e-09,1.000167,-0.437916,-0.305569,-0.238640,-0.087764,7.235031
B_B02,3004.0,-5.079490e-09,1.000166,-0.472908,-0.342006,-0.243177,-0.056500,7.088887
B_B03,3004.0,0.000000e+00,1.000167,-0.601352,-0.375050,-0.245208,-0.025725,6.982049
B_B04,3004.0,1.269873e-09,1.000167,-0.674172,-0.535866,-0.277683,0.134234,6.554642
B_B05,3004.0,-3.809618e-09,1.000167,-0.853333,-0.494034,-0.266148,0.126841,6.604018
B_B06,3004.0,-2.222277e-09,1.000167,-1.457834,-0.689422,-0.108007,0.394080,4.965311
B_B07,3004.0,-6.349363e-10,1.000165,-1.512497,-0.792072,-0.144206,0.600238,3.862572
B_B08,3004.0,2.539745e-09,1.000167,-1.629454,-0.808766,-0.076098,0.598003,3.655754
B_B09,3004.0,-1.904809e-09,1.000167,-1.322980,-0.614487,-0.122791,0.339416,5.554308
B_B11,3004.0,6.349363e-10,1.000166,-1.780347,-0.574518,-0.152278,0.511776,4.291829
B_B12,3004.0,-2.539745e-09,1.000166,-1.253420,-0.695889,-0.282453,0.420496,4.565513
B_B8A,3004.0,1.904809e-09,1.000166,-1.672702,-0.796822,-0.066732,0.609054,3.641253
NDVI,3004.0,-1.269873e-09,1.000166,-1.941107,-0.998290,0.018866,1.055994,1.332105
NDBI,3004.0,1.269873e-09,1.000166,-1.430537,-0.835718,-0.294360,0.806132,2.086175
NDMI,3004.0,-1.269873e-09,1.000166,-2.086175,-0.806132,0.294360,0.835718,1.430537
GNDVI,3004.0,-1.269873e-09,1.000167,-2.573327,-0.729395,0.046403,0.962884,1.398213
EVI,3004.0,1.269873e-09,1.000167,-2.027686,-0.894023,-0.228459,0.866460,2.037391
MNDWI,3004.0,1.269873e-09,1.000167,-1.172195,-0.655018,-0.326355,0.279340,3.498153
phenophase_date_doy_sin,3004.0,6.349363e-09,1.000168,-1.103110,-0.970889,-0.221367,0.928650,1.886893
phenophase_date_doy_cos,3004.0,1.904809e-09,1.000166,-0.921694,-0.788000,-0.519824,0.732576,2.347882
phenophase_date_month_sin,3004.0,5.714427e-09,1.000167,-1.022412,-0.689712,-0.689712,1.460900,2.702557
phenophase_date_month_cos,3004.0,2.857213e-09,1.000172,-1.019460,-0.761238,-0.055763,0.907934,1.871632
image_date_doy_sin,3004.0,6.349363e-09,1.000164,-1.086161,-0.968839,-0.114271,0.960567,1.884711
image_date_doy_cos,3004.0,4.762022e-09,1.000169,-0.942751,-0.779178,-0.554258,0.807363,2.348190
image_date_month_sin,3004.0,1.714328e-08,1.000166,-1.025201,-0.725308,-0.725308,1.213231,2.332447
image_date_month_cos,3004.0,9.524045e-10,1.000171,-0.990545,-0.738244,-0.048945,0.892656,1.834256
Longitude,3004.0,-1.904809e-09,1.000166,-1.094736,-0.850013,-0.460891,1.049296,1.904529
Latitude,3004.0,-2.222277e-09,1.000167,-1.772357,-0.889972,-0.076817,1.068720,1.392125

## Tune, Train, Evaluate, And Save Models

The Optuna objective is validation macro F1. Each final LightGBM model is refit on train + validation and evaluated on the held-out test set.

In [5]:
args = SimpleNamespace(trials=TRIALS, timeout=TIMEOUT, seed=SEED)
results = []

for target in TARGETS:
    y_train, y_val, y_test, encoder, class_weight = encode_target(
        df=df,
        train_idx=train_idx,
        val_idx=val_idx,
        test_idx=test_idx,
        target=target,
    )

    print("=" * 80)
    print(f"Target: {target}")
    print(f"Classes: {list(encoder.classes_)}")
    print(f"Class weights: {class_weight}")

    result = train_and_evaluate(
        target=target,
        x_train=x_train,
        x_val=x_val,
        x_test=x_test,
        y_train=y_train,
        y_val=y_val,
        y_test=y_test,
        encoder=encoder,
        class_weight=class_weight,
        feature_cols=feature_cols,
        args=args,
        output_dir=OUTPUT_DIR,
    )
    results.append(result)
    print(f"{target}: macro_f1={result['test_macro_f1']:.4f}, accuracy={result['test_accuracy']:.4f}\n")

results_df = pd.DataFrame(results).sort_values("test_macro_f1", ascending=False)
results_df.to_csv(OUTPUT_DIR / "model_results_summary.csv", index=False)
display(results_df)

[I 2026-05-02 21:01:23,649] A new study created in memory with name: crop_type_lightgbm_macro_f1

================================================================================
Target: crop_type
Classes: ['corn', 'rice', 'soybean']
Class weights: {0: 1.1417711896617255, 1: 0.7330405075646657, 2: 1.3158125273762593}

  0%|          | 0/25 [00:00<?, ?it/s]

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:01:31,279] Trial 0 finished with value: 0.9332122188732676 and parameters: {'boosting_type': 'dart', 'n_estimators': 1911, 'learning_rate': 0.026292183092620925, 'num_leaves': 26, 'max_depth': 3, 'min_child_samples': 11, 'subsample': 0.9397792655987208, 'subsample_freq': 5, 'colsample_bytree': 0.8686326600082205, 'reg_alpha': 1.5320059381854043e-08, 'reg_lambda': 5.360294728728285, 'min_split_gain': 0.41622132040021087, 'max_bin': 103, 'drop_rate': 0.06181974245763315, 'skip_drop': 0.22838315689740368}. Best is trial 0 with value: 0.9332122188732676.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:01:36,640] Trial 1 finished with value: 0.9033696762990716 and parameters: {'boosting_type': 'dart', 'n_estimators': 1250, 'learning_rate': 0.011211012365328633, 'num_leaves': 82, 'max_depth': 3, 'min_child_samples': 38, 'subsample': 0.7148628294821613, 'subsample_freq': 4, 'colsample_bytree': 0.9033291826268561, 'reg_alpha': 6.267062696005991e-07, 'reg_lambda': 0.00042472707398058225, 'min_split_gain': 0.29620728443102123, 'max_bin': 71, 'drop_rate': 0.1597353159373308, 'skip_drop': 0.2193668865811041}. Best is trial 0 with value: 0.9332122188732676.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:01:46,821] Trial 2 finished with value: 0.971220749071104 and parameters: {'boosting_type': 'dart', 'n_estimators': 2425, 'learning_rate': 0.04703026275515195, 'num_leaves': 44, 'max_depth': 3, 'min_child_samples': 84, 'subsample': 0.7480686221828206, 'subsample_freq': 1, 'colsample_bytree': 0.7728296095500716, 'reg_alpha': 2.039373116525212e-08, 'reg_lambda': 1.527156759251193, 'min_split_gain': 0.12938999080000846, 'max_bin': 190, 'drop_rate': 0.09169354750056452, 'skip_drop': 0.46404761482446766}. Best is trial 2 with value: 0.971220749071104.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:01:47,299] Trial 3 finished with value: 0.9759856511553074 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 2434, 'learning_rate': 0.04288672925586801, 'num_leaves': 121, 'max_depth': 11, 'min_child_samples': 74, 'subsample': 0.9648434057604025, 'subsample_freq': 1, 'colsample_bytree': 0.6381922880886154, 'reg_alpha': 2.5529693461039728e-08, 'reg_lambda': 8.471746987003668e-06, 'min_split_gain': 0.194338644844741, 'max_bin': 115}. Best is trial 3 with value: 0.9759856511553074.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:01:47,818] Trial 4 finished with value: 0.9805933140792028 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 918, 'learning_rate': 0.02251340595950629, 'num_leaves': 25, 'max_depth': 10, 'min_child_samples': 13, 'subsample': 0.9940991214702328, 'subsample_freq': 6, 'colsample_bytree': 0.6394220566903777, 'reg_alpha': 1.1212412169964432e-08, 'reg_lambda': 0.2183498289760726, 'min_split_gain': 0.35342867192380856, 'max_bin': 203}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:01:48,878] Trial 5 finished with value: 0.9745034449307148 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 1088, 'learning_rate': 0.006894301219471976, 'num_leaves': 112, 'max_depth': 8, 'min_child_samples': 43, 'subsample': 0.5786012576287107, 'subsample_freq': 3, 'colsample_bytree': 0.6963324949120362, 'reg_alpha': 0.036851536911881845, 'reg_lambda': 0.005470376807480391, 'min_split_gain': 0.44360637128816327, 'max_bin': 154}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:04,255] Trial 6 finished with value: 0.9745120946069501 and parameters: {'boosting_type': 'dart', 'n_estimators': 1974, 'learning_rate': 0.023703642788018935, 'num_leaves': 101, 'max_depth': 7, 'min_child_samples': 65, 'subsample': 0.7423934582613474, 'subsample_freq': 1, 'colsample_bytree': 0.598551142146987, 'reg_alpha': 1.9180621318615033e-08, 'reg_lambda': 0.005341874754868531, 'min_split_gain': 0.15717799053816334, 'max_bin': 161, 'drop_rate': 0.2287402890030014, 'skip_drop': 0.27450456040421245}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:05,787] Trial 7 finished with value: 0.9165458510653203 and parameters: {'boosting_type': 'dart', 'n_estimators': 803, 'learning_rate': 0.006189606672462582, 'num_leaves': 43, 'max_depth': 3, 'min_child_samples': 112, 'subsample': 0.9136541708039876, 'subsample_freq': 5, 'colsample_bytree': 0.942157265584473, 'reg_alpha': 0.1710207048797339, 'reg_lambda': 4.776728196949699e-07, 'min_split_gain': 0.4462794992449889, 'max_bin': 167, 'drop_rate': 0.2057112356877344, 'skip_drop': 0.7272639099464453}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:06,402] Trial 8 finished with value: 0.978115009795819 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 801, 'learning_rate': 0.016340262437673857, 'num_leaves': 106, 'max_depth': 11, 'min_child_samples': 5, 'subsample': 0.7798362861599046, 'subsample_freq': 3, 'colsample_bytree': 0.6499485147118287, 'reg_alpha': 1.1989147575590843e-07, 'reg_lambda': 1.0927895733904103e-05, 'min_split_gain': 0.4714548519562596, 'max_bin': 125}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:13,044] Trial 9 finished with value: 0.9728373685876429 and parameters: {'boosting_type': 'dart', 'n_estimators': 1100, 'learning_rate': 0.07397964260767156, 'num_leaves': 124, 'max_depth': 4, 'min_child_samples': 62, 'subsample': 0.6853952394175464, 'subsample_freq': 2, 'colsample_bytree': 0.5665991263095398, 'reg_alpha': 0.003062520509464317, 'reg_lambda': 0.0003342806277473177, 'min_split_gain': 0.025739375624994676, 'max_bin': 116, 'drop_rate': 0.22890115377233036, 'skip_drop': 0.2676933234668807}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:13,408] Trial 10 finished with value: 0.97166097458259 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 313, 'learning_rate': 0.01274591951593693, 'num_leaves': 10, 'max_depth': 8, 'min_child_samples': 30, 'subsample': 0.8444694352468389, 'subsample_freq': 7, 'colsample_bytree': 0.7497318396751259, 'reg_alpha': 1.0498796393327273e-05, 'reg_lambda': 0.21495810818775887, 'min_split_gain': 0.321822554190479, 'max_bin': 239}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:14,010] Trial 11 finished with value: 0.9777358438743294 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 611, 'learning_rate': 0.016710391849402692, 'num_leaves': 77, 'max_depth': 12, 'min_child_samples': 5, 'subsample': 0.8406353983164585, 'subsample_freq': 7, 'colsample_bytree': 0.6789603415722625, 'reg_alpha': 2.3788433031217224e-05, 'reg_lambda': 5.988530921734077e-08, 'min_split_gain': 0.494989239759853, 'max_bin': 226}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:14,324] Trial 12 finished with value: 0.9614626322905325 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 1575, 'learning_rate': 0.030399829088499402, 'num_leaves': 56, 'max_depth': 10, 'min_child_samples': 19, 'subsample': 0.6065300869039434, 'subsample_freq': 5, 'colsample_bytree': 0.6971252273817387, 'reg_alpha': 5.832212752183789, 'reg_lambda': 5.43905898266636e-06, 'min_split_gain': 0.3543706743208145, 'max_bin': 200}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:15,117] Trial 13 finished with value: 0.9793179347349228 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 723, 'learning_rate': 0.01547983555264149, 'num_leaves': 96, 'max_depth': 10, 'min_child_samples': 26, 'subsample': 0.8420751809098664, 'subsample_freq': 3, 'colsample_bytree': 0.5516639069306593, 'reg_alpha': 8.519301321425888e-07, 'reg_lambda': 0.10699113562545419, 'min_split_gain': 0.37811810898404574, 'max_bin': 141}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:15,784] Trial 14 finished with value: 0.978931147581326 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 441, 'learning_rate': 0.010881944135803718, 'num_leaves': 92, 'max_depth': 9, 'min_child_samples': 25, 'subsample': 0.8746614961144514, 'subsample_freq': 6, 'colsample_bytree': 0.5502102641475255, 'reg_alpha': 2.905490007353838e-06, 'reg_lambda': 0.07956857590417335, 'min_split_gain': 0.3758558487456328, 'max_bin': 218}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:16,593] Trial 15 finished with value: 0.9725992823693973 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 810, 'learning_rate': 0.008331327594347088, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 49, 'subsample': 0.9991441516347556, 'subsample_freq': 3, 'colsample_bytree': 0.608858087026207, 'reg_alpha': 0.0001673789745573068, 'reg_lambda': 0.041616196151704955, 'min_split_gain': 0.2714581132380469, 'max_bin': 250}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:16,966] Trial 16 finished with value: 0.9756864246806617 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 1512, 'learning_rate': 0.03964446721983963, 'num_leaves': 21, 'max_depth': 6, 'min_child_samples': 99, 'subsample': 0.8075785274354857, 'subsample_freq': 4, 'colsample_bytree': 0.8314597709187465, 'reg_alpha': 4.866476180262578e-07, 'reg_lambda': 0.7751952310012651, 'min_split_gain': 0.2279549056143347, 'max_bin': 185}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:17,443] Trial 17 finished with value: 0.9789788881618035 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 577, 'learning_rate': 0.01894382406893618, 'num_leaves': 70, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.8975096014665436, 'subsample_freq': 6, 'colsample_bytree': 0.7216903488244995, 'reg_alpha': 5.110866438251067e-07, 'reg_lambda': 0.008349362462520844, 'min_split_gain': 0.3681465439943041, 'max_bin': 141}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:17,796] Trial 18 finished with value: 0.9747571520150261 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 977, 'learning_rate': 0.031238957320509513, 'num_leaves': 90, 'max_depth': 12, 'min_child_samples': 31, 'subsample': 0.9997635233573302, 'subsample_freq': 6, 'colsample_bytree': 0.6041226846368308, 'reg_alpha': 6.602183491225157e-05, 'reg_lambda': 3.522614681479353, 'min_split_gain': 0.3934053326157454, 'max_bin': 85}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:18,536] Trial 19 finished with value: 0.9761173019929789 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 1244, 'learning_rate': 0.014005405055995875, 'num_leaves': 41, 'max_depth': 9, 'min_child_samples': 18, 'subsample': 0.6501726873282037, 'subsample_freq': 2, 'colsample_bytree': 0.8353058466581745, 'reg_alpha': 0.0008849299239384577, 'reg_lambda': 0.19392610340795396, 'min_split_gain': 0.31875252942917176, 'max_bin': 205}. Best is trial 4 with value: 0.9805933140792028.
[I 2026-05-02 21:02:18,736] Trial 20 finished with value: 0.9786856405074621 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 1713, 'learning_rate': 0.06174620451164098, 'num_leaves': 27, 'max_depth': 7, 'min_child_samples': 39, 'subsample': 0.9459601154097603, 'subsample_freq': 4, 'colsample_bytree': 0.643431833415892, 'reg_alpha': 3.878406728656666e-06, 'reg_lambda': 0.0013469034959364692, 'min_split_gain': 0.23903108972516474, 'max_bin': 175}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:19,169] Trial 21 finished with value: 0.9778355150513981 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 550, 'learning_rate': 0.021201236264850546, 'num_leaves': 70, 'max_depth': 10, 'min_child_samples': 52, 'subsample': 0.893154617227373, 'subsample_freq': 6, 'colsample_bytree': 0.734635054820615, 'reg_alpha': 3.1488601461317295e-07, 'reg_lambda': 0.009665312836966401, 'min_split_gain': 0.3417340034725124, 'max_bin': 142}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:19,632] Trial 22 finished with value: 0.9793532123112222 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 642, 'learning_rate': 0.01934280277257778, 'num_leaves': 60, 'max_depth': 10, 'min_child_samples': 20, 'subsample': 0.865282644553021, 'subsample_freq': 7, 'colsample_bytree': 0.7269652007426125, 'reg_alpha': 7.679037627619446e-08, 'reg_lambda': 0.02454014202048799, 'min_split_gain': 0.39356708037535953, 'max_bin': 137}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:20,069] Trial 23 finished with value: 0.9732742277263909 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 844, 'learning_rate': 0.020157217227411917, 'num_leaves': 9, 'max_depth': 11, 'min_child_samples': 16, 'subsample': 0.8267900404696227, 'subsample_freq': 7, 'colsample_bytree': 0.7996530442682412, 'reg_alpha': 1.0129440148503827e-07, 'reg_lambda': 0.04434737349634867, 'min_split_gain': 0.4108405282225152, 'max_bin': 138}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:20,882] Trial 24 finished with value: 0.9779849114647391 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 669, 'learning_rate': 0.008569342544389421, 'num_leaves': 56, 'max_depth': 9, 'min_child_samples': 24, 'subsample': 0.7956330496831995, 'subsample_freq': 7, 'colsample_bytree': 0.592799685234933, 'reg_alpha': 2.0063005323234014e-06, 'reg_lambda': 0.49663723207053906, 'min_split_gain': 0.2680034509316092, 'max_bin': 102}. Best is trial 4 with value: 0.9805933140792028.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
[I 2026-05-02 21:02:21,546] A new study created in memory with name: phenophase_name_lightgbm_macro_f1

crop_type: macro_f1=0.9879, accuracy=0.9894

================================================================================
Target: phenophase_name
Classes: ['Dormancy', 'Greenup', 'Maturity', 'MidGreenup', 'MidSenescence', 'Peak', 'Senescence']
Class weights: {0: 0.9731130547457079, 1: 0.9494310998735778, 2: 0.9980066445182725, 3: 1.0266575529733424, 4: 0.9494310998735778, 5: 1.0864376130198914, 6: 1.0315934065934067}

  0%|          | 0/25 [00:00<?, ?it/s]

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:36,319] Trial 0 finished with value: 0.9889641417388441 and parameters: {'boosting_type': 'dart', 'n_estimators': 1911, 'learning_rate': 0.026292183092620925, 'num_leaves': 26, 'max_depth': 3, 'min_child_samples': 11, 'subsample': 0.9397792655987208, 'subsample_freq': 5, 'colsample_bytree': 0.8686326600082205, 'reg_alpha': 1.5320059381854043e-08, 'reg_lambda': 5.360294728728285, 'min_split_gain': 0.41622132040021087, 'max_bin': 103, 'drop_rate': 0.06181974245763315, 'skip_drop': 0.22838315689740368}. Best is trial 0 with value: 0.9889641417388441.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:02:48,043] Trial 1 finished with value: 0.9864277766159298 and parameters: {'boosting_type': 'dart', 'n_estimators': 1250, 'learning_rate': 0.011211012365328633, 'num_leaves': 82, 'max_depth': 3, 'min_child_samples': 38, 'subsample': 0.7148628294821613, 'subsample_freq': 4, 'colsample_bytree': 0.9033291826268561, 'reg_alpha': 6.267062696005991e-07, 'reg_lambda': 0.00042472707398058225, 'min_split_gain': 0.29620728443102123, 'max_bin': 71, 'drop_rate': 0.1597353159373308, 'skip_drop': 0.2193668865811041}. Best is trial 0 with value: 0.9889641417388441.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:02,412] Trial 2 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'dart', 'n_estimators': 2425, 'learning_rate': 0.04703026275515195, 'num_leaves': 44, 'max_depth': 3, 'min_child_samples': 84, 'subsample': 0.7480686221828206, 'subsample_freq': 1, 'colsample_bytree': 0.7728296095500716, 'reg_alpha': 2.039373116525212e-08, 'reg_lambda': 1.527156759251193, 'min_split_gain': 0.12938999080000846, 'max_bin': 190, 'drop_rate': 0.09169354750056452, 'skip_drop': 0.46404761482446766}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:02,716] Trial 3 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 2434, 'learning_rate': 0.04288672925586801, 'num_leaves': 121, 'max_depth': 11, 'min_child_samples': 74, 'subsample': 0.9648434057604025, 'subsample_freq': 1, 'colsample_bytree': 0.6381922880886154, 'reg_alpha': 2.5529693461039728e-08, 'reg_lambda': 8.471746987003668e-06, 'min_split_gain': 0.194338644844741, 'max_bin': 115}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:03,095] Trial 4 finished with value: 0.9916733136456618 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 918, 'learning_rate': 0.02251340595950629, 'num_leaves': 25, 'max_depth': 10, 'min_child_samples': 13, 'subsample': 0.9940991214702328, 'subsample_freq': 6, 'colsample_bytree': 0.6394220566903777, 'reg_alpha': 1.1212412169964432e-08, 'reg_lambda': 0.2183498289760726, 'min_split_gain': 0.35342867192380856, 'max_bin': 203}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:04,185] Trial 5 finished with value: 0.9916826544312773 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 1088, 'learning_rate': 0.006894301219471976, 'num_leaves': 112, 'max_depth': 8, 'min_child_samples': 43, 'subsample': 0.5786012576287107, 'subsample_freq': 3, 'colsample_bytree': 0.6963324949120362, 'reg_alpha': 0.036851536911881845, 'reg_lambda': 0.005470376807480391, 'min_split_gain': 0.44360637128816327, 'max_bin': 154}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:24,255] Trial 6 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'dart', 'n_estimators': 1974, 'learning_rate': 0.023703642788018935, 'num_leaves': 101, 'max_depth': 7, 'min_child_samples': 65, 'subsample': 0.7423934582613474, 'subsample_freq': 1, 'colsample_bytree': 0.598551142146987, 'reg_alpha': 1.9180621318615033e-08, 'reg_lambda': 0.005341874754868531, 'min_split_gain': 0.15717799053816334, 'max_bin': 161, 'drop_rate': 0.2287402890030014, 'skip_drop': 0.27450456040421245}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:27,128] Trial 7 finished with value: 0.9864123812135153 and parameters: {'boosting_type': 'dart', 'n_estimators': 803, 'learning_rate': 0.006189606672462582, 'num_leaves': 43, 'max_depth': 3, 'min_child_samples': 112, 'subsample': 0.9136541708039876, 'subsample_freq': 5, 'colsample_bytree': 0.942157265584473, 'reg_alpha': 0.1710207048797339, 'reg_lambda': 4.776728196949699e-07, 'min_split_gain': 0.4462794992449889, 'max_bin': 167, 'drop_rate': 0.2057112356877344, 'skip_drop': 0.7272639099464453}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:27,778] Trial 8 finished with value: 0.9930761450687118 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 801, 'learning_rate': 0.016340262437673857, 'num_leaves': 106, 'max_depth': 11, 'min_child_samples': 5, 'subsample': 0.7798362861599046, 'subsample_freq': 3, 'colsample_bytree': 0.6499485147118287, 'reg_alpha': 1.1989147575590843e-07, 'reg_lambda': 1.0927895733904103e-05, 'min_split_gain': 0.4714548519562596, 'max_bin': 125}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:38,630] Trial 9 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'dart', 'n_estimators': 1100, 'learning_rate': 0.07397964260767156, 'num_leaves': 124, 'max_depth': 4, 'min_child_samples': 62, 'subsample': 0.6853952394175464, 'subsample_freq': 2, 'colsample_bytree': 0.5665991263095398, 'reg_alpha': 0.003062520509464317, 'reg_lambda': 0.0003342806277473177, 'min_split_gain': 0.025739375624994676, 'max_bin': 116, 'drop_rate': 0.22890115377233036, 'skip_drop': 0.2676933234668807}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:39,351] Trial 10 finished with value: 0.9917374404349297 and parameters: {'boosting_type': 'dart', 'n_estimators': 313, 'learning_rate': 0.07352059504020737, 'num_leaves': 60, 'max_depth': 5, 'min_child_samples': 107, 'subsample': 0.8444694352468389, 'subsample_freq': 7, 'colsample_bytree': 0.7964012084816818, 'reg_alpha': 2.4118106550539762e-05, 'reg_lambda': 8.530248590348545, 'min_split_gain': 0.053080011731439836, 'max_bin': 239, 'drop_rate': 0.056941687485595374, 'skip_drop': 0.5725743563439207}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:39,630] Trial 11 finished with value: 0.9930761450687118 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 2489, 'learning_rate': 0.042003338220164485, 'num_leaves': 71, 'max_depth': 12, 'min_child_samples': 89, 'subsample': 0.8158013758563558, 'subsample_freq': 1, 'colsample_bytree': 0.7475535570792389, 'reg_alpha': 1.344933695762981e-05, 'reg_lambda': 2.0057322817130592e-08, 'min_split_gain': 0.17236826909900563, 'max_bin': 200}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:40,140] Trial 12 finished with value: 0.9849190325250695 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 2483, 'learning_rate': 0.04118259742559533, 'num_leaves': 12, 'max_depth': 7, 'min_child_samples': 84, 'subsample': 0.6312285575229553, 'subsample_freq': 1, 'colsample_bytree': 0.7957225932227743, 'reg_alpha': 4.875750956053446, 'reg_lambda': 7.908715883827235e-07, 'min_split_gain': 0.17076437197278674, 'max_bin': 77}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:40,444] Trial 13 finished with value: 0.9930761450687118 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 2069, 'learning_rate': 0.04309131409324666, 'num_leaves': 51, 'max_depth': 9, 'min_child_samples': 85, 'subsample': 0.8670393826376369, 'subsample_freq': 2, 'colsample_bytree': 0.7164202269486517, 'reg_alpha': 2.5242581590195644e-06, 'reg_lambda': 1.277797918458278e-05, 'min_split_gain': 0.1125839878817078, 'max_bin': 200}. Best is trial 2 with value: 0.9944627474448027.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:50,212] Trial 14 finished with value: 0.9958632362897765 and parameters: {'boosting_type': 'dart', 'n_estimators': 1707, 'learning_rate': 0.051271499007195756, 'num_leaves': 83, 'max_depth': 6, 'min_child_samples': 67, 'subsample': 0.9959102239722796, 'subsample_freq': 2, 'colsample_bytree': 0.8499410376884735, 'reg_alpha': 0.00019821075029436729, 'reg_lambda': 0.3332082387313631, 'min_split_gain': 0.24572656394671957, 'max_bin': 246, 'drop_rate': 0.1118884990658506, 'skip_drop': 0.47806651407951567}. Best is trial 14 with value: 0.9958632362897765.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:03:57,809] Trial 15 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'dart', 'n_estimators': 1562, 'learning_rate': 0.05338569753680149, 'num_leaves': 82, 'max_depth': 5, 'min_child_samples': 48, 'subsample': 0.6653971714056914, 'subsample_freq': 2, 'colsample_bytree': 0.8452197254896915, 'reg_alpha': 0.0005635843162463801, 'reg_lambda': 0.21956774205104782, 'min_split_gain': 0.26002510452595606, 'max_bin': 255, 'drop_rate': 0.1108275276346196, 'skip_drop': 0.5224091877929196}. Best is trial 14 with value: 0.9958632362897765.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:04:07,645] Trial 16 finished with value: 0.9931571659854164 and parameters: {'boosting_type': 'dart', 'n_estimators': 1609, 'learning_rate': 0.029120474875308437, 'num_leaves': 87, 'max_depth': 2, 'min_child_samples': 97, 'subsample': 0.8846851901911907, 'subsample_freq': 3, 'colsample_bytree': 0.9983014229823602, 'reg_alpha': 6.3767400818081e-05, 'reg_lambda': 0.2461222789731571, 'min_split_gain': 0.09074626663780919, 'max_bin': 229, 'drop_rate': 0.10724868346373616, 'skip_drop': 0.42096398672662855}. Best is trial 14 with value: 0.9958632362897765.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:04:24,624] Trial 17 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'dart', 'n_estimators': 2149, 'learning_rate': 0.012718009515357526, 'num_leaves': 38, 'max_depth': 6, 'min_child_samples': 54, 'subsample': 0.7829006541147064, 'subsample_freq': 2, 'colsample_bytree': 0.818205339800067, 'reg_alpha': 0.0027320448897408243, 'reg_lambda': 0.014897213139880634, 'min_split_gain': 0.32013539042173933, 'max_bin': 218, 'drop_rate': 0.14976551945801367, 'skip_drop': 0.4159001141083127}. Best is trial 14 with value: 0.9958632362897765.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:04:26,835] Trial 18 finished with value: 0.9930761450687118 and parameters: {'boosting_type': 'dart', 'n_estimators': 1681, 'learning_rate': 0.05806239161087127, 'num_leaves': 68, 'max_depth': 5, 'min_child_samples': 119, 'subsample': 0.5582404891407302, 'subsample_freq': 4, 'colsample_bytree': 0.7460542667146683, 'reg_alpha': 1.5081413758870102e-06, 'reg_lambda': 0.6910009504954918, 'min_split_gain': 0.22453686232252118, 'max_bin': 179, 'drop_rate': 0.02108182722846244, 'skip_drop': 0.6801314629317101}. Best is trial 14 with value: 0.9958632362897765.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:04:37,751] Trial 19 finished with value: 0.9930761450687118 and parameters: {'boosting_type': 'dart', 'n_estimators': 2219, 'learning_rate': 0.03156777280070376, 'num_leaves': 60, 'max_depth': 2, 'min_child_samples': 75, 'subsample': 0.8165710102412473, 'subsample_freq': 3, 'colsample_bytree': 0.9203511628701814, 'reg_alpha': 0.9650035038231072, 'reg_lambda': 0.032215605824817584, 'min_split_gain': 0.12007149479440907, 'max_bin': 252, 'drop_rate': 0.0849781734316627, 'skip_drop': 0.523234877023012}. Best is trial 14 with value: 0.9958632362897765.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:04:52,222] Trial 20 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'dart', 'n_estimators': 1797, 'learning_rate': 0.05533746595998233, 'num_leaves': 35, 'max_depth': 6, 'min_child_samples': 32, 'subsample': 0.7447130203234654, 'subsample_freq': 2, 'colsample_bytree': 0.8787776952894941, 'reg_alpha': 0.020978385174500055, 'reg_lambda': 2.6519995640464646, 'min_split_gain': 0.37839054320394044, 'max_bin': 182, 'drop_rate': 0.16627973530726795, 'skip_drop': 0.34749379183512025}. Best is trial 14 with value: 0.9958632362897765.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:04:52,565] Trial 21 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 2312, 'learning_rate': 0.03563761621524526, 'num_leaves': 127, 'max_depth': 9, 'min_child_samples': 71, 'subsample': 0.9858203305008466, 'subsample_freq': 1, 'colsample_bytree': 0.6691227399121057, 'reg_alpha': 2.0943126242126907e-07, 'reg_lambda': 2.745151437035401e-05, 'min_split_gain': 0.22279528519444625, 'max_bin': 140}. Best is trial 14 with value: 0.9958632362897765.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:04:52,778] Trial 22 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 2316, 'learning_rate': 0.05371472046459301, 'num_leaves': 97, 'max_depth': 12, 'min_child_samples': 76, 'subsample': 0.9452784216739549, 'subsample_freq': 1, 'colsample_bytree': 0.6028173031250643, 'reg_alpha': 1.3244872162106096e-07, 'reg_lambda': 8.838278780543827e-05, 'min_split_gain': 0.20709025673897125, 'max_bin': 139}. Best is trial 14 with value: 0.9958632362897765.
[I 2026-05-02 21:04:52,967] Trial 23 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'gbdt', 'n_estimators': 1441, 'learning_rate': 0.06763116421283487, 'num_leaves': 51, 'max_depth': 8, 'min_child_samples': 97, 'subsample': 0.9564944710638991, 'subsample_freq': 1, 'colsample_bytree': 0.7563400577595041, 'reg_alpha': 9.14916351775478e-06, 'reg_lambda': 1.3766046835429285e-06, 'min_split_gain': 0.2534087470508233, 'max_bin': 96}. Best is trial 14 with value: 0.9958632362897765.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[I 2026-05-02 21:05:02,577] Trial 24 finished with value: 0.9944627474448027 and parameters: {'boosting_type': 'dart', 'n_estimators': 1832, 'learning_rate': 0.016946175855470973, 'num_leaves': 92, 'max_depth': 10, 'min_child_samples': 61, 'subsample': 0.9136661206825267, 'subsample_freq': 2, 'colsample_bytree': 0.8341095430446422, 'reg_alpha': 0.00023124692333282497, 'reg_lambda': 0.0014180293357784943, 'min_split_gain': 0.28697782326716076, 'max_bin': 182, 'drop_rate': 0.1169774300196342, 'skip_drop': 0.6049844883377299}. Best is trial 14 with value: 0.9958632362897765.

c:\Stuffs\Apps\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

phenophase_name: macro_f1=0.9912, accuracy=0.9915

,target,model,test_macro_f1,test_weighted_f1,test_accuracy,best_val_macro_f1,classes
1,phenophase_name,lightgbm_optuna,0.991215,0.991466,0.99148,0.995863,"Dormancy, Greenup, Maturity, MidGreenup, MidSe..."
0,crop_type,lightgbm_optuna,0.987851,0.989356,0.98935,0.980593,"corn, rice, soybean"

## Saved Artifacts

In [6]:
for target in TARGETS:
    target_dir = OUTPUT_DIR / target
    print(f"{target} model: {target_dir / 'lightgbm_model.joblib'}")
    print(f"{target} encoder: {target_dir / 'label_encoder.joblib'}")
    print(f"{target} report: {target_dir / 'classification_report.txt'}")
    print(f"{target} feature importance: {target_dir / 'feature_importance.csv'}")
print(f"Preprocessing: {OUTPUT_DIR / 'preprocessing'}")
print(f"Summary: {OUTPUT_DIR / 'model_results_summary.csv'}")

crop_type model: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\crop_type\lightgbm_model.joblib
crop_type encoder: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\crop_type\label_encoder.joblib
crop_type report: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\crop_type\classification_report.txt
crop_type feature importance: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\crop_type\feature_importance.csv
phenophase_name model: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\phenophase_name\lightgbm_model.joblib
phenophase_name encoder: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\phenophase_name\label_encoder.joblib
phenophase_name report: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\phenophase_name\classification_report.txt
phenophase_name feature importance: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\phenophase_name\feature_importance.csv
Preprocessing: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\preprocessing
Summary: d:\!Reno\AIG\Code\lightgbm_notebook_full_date_location\model_results_summary.csv